import { IResource } from "../types";
export interface Ihydrate extends IResource {
  name: "hydrate";
}

export const hydrate: Ihydrate = {
  name: "hydrate",
  description:
    "hydrate lets you display React components inside a browser DOM node whose HTML content was previously generated by react-dom/server in React 17 and below.",
  example: {
    code: "hydrate(reactNode, domNode, callback?)",
  },
  usage: [
    {
      title: "Hydrating server-rendered HTML ",
      href: "https://react.dev/reference/react-dom/hydrate#hydrating-server-rendered-html",
    },
    {
      title: "Suppressing unavoidable hydration mismatch errors ",
      href: "https://react.dev/reference/react-dom/hydrate#suppressing-unavoidable-hydration-mismatch-errors",
    },
    {
      title: "Handling different client and server content ",
      href: "https://react.dev/reference/react-dom/hydrate#handling-different-client-and-server-content",
    },
  ],
  link: "https://react.dev/reference/react-dom/hydrate",
};
